# Generated by Django 5.1.6 on 2025-05-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='transportation_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
