# Generated by Django 5.1.6 on 2025-05-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ad_transportation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
