# Generated by Django 5.1.6 on 2025-12-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_ad_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="reward",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="مكافأة",
                max_digits=10,
                null=True,
            ),
        ),
    ]
