# Generated by Django 5.1.6 on 2025-12-23 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_ad_reward"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CardAd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("card_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("lost", "Lost"), ("found", "Found")], max_length=10
                    ),
                ),
                ("location_description", models.TextField()),
                ("exact_address", models.CharField(blank=True, max_length=255)),
                (
                    "transportation_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date_time", models.DateTimeField()),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="ads_images/"),
                ),
                (
                    "reward",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="مكافأة",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "card_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.cardtype",
                    ),
                ),
            ],
        ),
    ]
