# Generated by Django 5.1.6 on 2025-12-23 06:51

from django.db import migrations


def add_initial_card_types(apps, schema_editor):
    CardType = apps.get_model('api', 'CardType')
    CardType.objects.bulk_create([
        CardType(name='Visa'),
        CardType(name='National Card'),
        CardType(name='Other'),
    ])


def remove_initial_card_types(apps, schema_editor):
    CardType = apps.get_model('api', 'CardType')
    CardType.objects.filter(name__in=['Visa', 'National Card', 'Other']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_cardtype_cardad"),
    ]

    operations = [
        migrations.RunPython(add_initial_card_types, remove_initial_card_types),
    ]
