# Generated by Django 5.1.6 on 2025-12-23 06:54

from django.db import migrations


def rename_card_name_to_card_number(apps, schema_editor):
    # Use raw SQL to rename the column in SQLite
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # SQLite 3.25.0+ supports ALTER TABLE RENAME COLUMN
        # Check if column exists first
        cursor.execute("PRAGMA table_info(api_cardad)")
        columns = [row[1] for row in cursor.fetchall()]
        
        if 'card_name' in columns and 'card_number' not in columns:
            # Use ALTER TABLE RENAME COLUMN (SQLite 3.25.0+)
            try:
                cursor.execute(
                    "ALTER TABLE api_cardad RENAME COLUMN card_name TO card_number"
                )
            except Exception as e:
                # Fallback for older SQLite: recreate table
                # Get all column info
                cursor.execute("PRAGMA table_info(api_cardad)")
                column_info = cursor.fetchall()
                
                # Build new table with renamed column
                cursor.execute("""
                    CREATE TABLE api_cardad_new (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        title VARCHAR(255) NOT NULL,
                        card_number VARCHAR(255) NOT NULL,
                        status VARCHAR(10) NOT NULL,
                        location_description TEXT NOT NULL,
                        exact_address VARCHAR(255) NOT NULL,
                        transportation_type VARCHAR(255),
                        date_time DATETIME NOT NULL,
                        comments TEXT,
                        image VARCHAR(100),
                        reward DECIMAL(10, 2),
                        is_resolved BOOLEAN NOT NULL,
                        created_at DATETIME NOT NULL,
                        user_id INTEGER NOT NULL REFERENCES api_user(id),
                        card_type_id INTEGER REFERENCES api_cardtype(id)
                    )
                """)
                cursor.execute("""
                    INSERT INTO api_cardad_new 
                    (id, title, card_number, status, location_description, exact_address, 
                     transportation_type, date_time, comments, image, reward, is_resolved, 
                     created_at, user_id, card_type_id)
                    SELECT id, title, card_name, status, location_description, exact_address,
                           transportation_type, date_time, comments, image, reward, is_resolved,
                           created_at, user_id, card_type_id
                    FROM api_cardad
                """)
                cursor.execute("DROP TABLE api_cardad")
                cursor.execute("ALTER TABLE api_cardad_new RENAME TO api_cardad")


def reverse_rename(apps, schema_editor):
    # Reverse operation
    with schema_editor.connection.cursor() as cursor:
        try:
            cursor.execute(
                "ALTER TABLE api_cardad RENAME COLUMN card_number TO card_name"
            )
        except Exception:
            # Fallback for older SQLite
            cursor.execute("""
                CREATE TABLE api_cardad_old (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    title VARCHAR(255) NOT NULL,
                    card_name VARCHAR(255) NOT NULL,
                    status VARCHAR(10) NOT NULL,
                    location_description TEXT NOT NULL,
                    exact_address VARCHAR(255) NOT NULL,
                    transportation_type VARCHAR(255),
                    date_time DATETIME NOT NULL,
                    comments TEXT,
                    image VARCHAR(100),
                    reward DECIMAL(10, 2),
                    is_resolved BOOLEAN NOT NULL,
                    created_at DATETIME NOT NULL,
                    user_id INTEGER NOT NULL REFERENCES api_user(id),
                    card_type_id INTEGER REFERENCES api_cardtype(id)
                )
            """)
            cursor.execute("""
                INSERT INTO api_cardad_old 
                (id, title, card_name, status, location_description, exact_address, 
                 transportation_type, date_time, comments, image, reward, is_resolved, 
                 created_at, user_id, card_type_id)
                SELECT id, title, card_number, status, location_description, exact_address,
                       transportation_type, date_time, comments, image, reward, is_resolved,
                       created_at, user_id, card_type_id
                FROM api_cardad
            """)
            cursor.execute("DROP TABLE api_cardad")
            cursor.execute("ALTER TABLE api_cardad_old RENAME TO api_cardad")


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_auto_20251223_0851"),
    ]

    operations = [
        migrations.RunPython(rename_card_name_to_card_number, reverse_rename),
    ]
